***************
*** 3,20 ****
  # Must set below, and edit version in bjlaunch.rc and in bjmanifest.xml or gfmanifest.xml
  
  # For BlueJ
- #APPNAME=\"BlueJ\"
- #GREENFOOTDEF=
- #EXECNAME=bjlaunch.exe
- #REQUIREDJAVA=\"1.5\"
  
  # For Greenfoot
- APPNAME=\"Greenfoot\"
- GREENFOOTDEF=-DGREENFOOT
- EXECNAME=gflaunch.exe
- REQUIREDJAVA=\"1.6\"
  
- JDKDIR=/c/Program Files/Java/jdk1.6.0_05
  
  OBJECTS = resources.o bjlaunch.o javatest.o javaprops.o bjdialog.o
  
--- 3,20 ----
  # Must set below, and edit version in bjlaunch.rc and in bjmanifest.xml or gfmanifest.xml
  
  # For BlueJ
+ APPNAME=\"BlueJ\"
+ GREENFOOTDEF=
+ EXECNAME=bjlaunch.exe
+ REQUIREDJAVA=\"1.5\"
  
  # For Greenfoot
+ #APPNAME=\"Greenfoot\"
+ #GREENFOOTDEF=-DGREENFOOT
+ #EXECNAME=gflaunch.exe
+ #REQUIREDJAVA=\"1.6\"
  
+ JDKDIR=/c/Program Files/Java/jdk1.6.0_22
  
  OBJECTS = resources.o bjlaunch.o javatest.o javaprops.o bjdialog.o
  
